# Generated by Django 2.1.7 on 2019-02-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gallerypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='image',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
